[tool.isort]
profile = "black"
skip_glob = [
    "geometric_kernel/__init__.py",
]


[tool.mypy]
ignore_missing_imports = true
strict_optional = false
allow_redefinition = true
# --strict
disallow_any_generics = true
disallow_subclassing_any = true 
disallow_untyped_calls = true 
disallow_untyped_defs = true
disallow_incomplete_defs = true 
check_untyped_defs = true 
disallow_untyped_decorators = true 
no_implicit_optional = true
warn_redundant_casts = true 
warn_unused_ignores = true
warn_return_any = true 
implicit_reexport = false
strict_equality = true
# --strict end


[tool.black]
line-length = 88
target-version = ['py37']
# Remaining settings for compatibility with black
# See https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true