[tool.isort]
profile = "black"
skip_glob = [
    "geometric_kernel/__init__.py",
]
known_third_party = [
    "lab",
]


[tool.mypy]
ignore_missing_imports = true
strict_optional = false
allow_redefinition = true


[tool.black]
line-length = 88
target-version = ['py37']
# Remaining settings for compatibility with black
# See https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true