[tool.poetry]
name = "GeometricKernels"
version = "0.1.0"
description = "A Python Package for Geometric Kernels"
authors = ["Geometric Kernel Devs"]
packages = [{include = "geometric_kernels", from = "."}]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.5"
jupyterlab = "^3.1.1"
seaborn = "^0.11.1"
potpourri3d = "^0.0.4"
robust_laplacian = "^0.2.2"
meshzoo = "^0.7.5"
polyscope = "^1.2.0"
eagerpy = "^0.30.0"
gpytorch = {version = "^1.5.1", optional = true}
torch = {version = "^1.8.1", optional = true}
gpflow = {version = "^2.2.1", optional = true}
tensorflow = {version = "^2.6.0", optional = true}
tensorflow-probability = {version = "^0.13.0", optional = true}
multipledispatch = "^0.6.0"

[tool.poetry.extras]
tensorflow = ["gpflow", "tensorflow", "tensorflow-probability"]
pytorch = ["gpytorch", "torch"]
numpy = []

[tool.poetry.dev-dependencies]
mypy = "0.711"
pylint = "2.3.1"
pytest = "^5.3.5"
black = "20.8b1"
pytest-cov = "^2.8.1"
pytest-mypy = "^0.6.1"
pytest-pylint = "^0.17.0"
taskipy = "^1.2.0"
pytest-black = "^0.3.8,!=0.3.10"
pytest-isort = "^1.0.0"
typing-extensions = "^3.7.0"

[tool.taskipy.tasks]
# TensorFlow and GPflow
lint_tensorflow = "pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint geometric_kernels --ignore='tests/integration/gpytorch'"
quicktest_tensorflow = "pytest -x --ff -rn -wignore --ignore='tests/integration/gpytorch'"
check_format_tensorflow = "pytest -v --cache-clear --black --isort -m 'black or isort' --ignore='tests/integration/gpytorch'"
test_tensorflow = "pytest --pylint --mypy --black --isort --cache-clear -ra -v --cov geometric_kernels --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml -o junit_family=xunit2 --ignore='tests/integration/gpytorch' && task lint_tensorflow"

# PyTorch and GPyTorch
lint_pytorch = "pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint geometric_kernels --ignore='tests/integration/gpflow'"
quicktest_pytorch = "pytest -x --ff -rn -wignore --ignore='tests/integration/gpflow'"
check_format_pytorch = "pytest -v --cache-clear --black --isort -m 'black or isort' --ignore='tests/integration/gpflow'"
test_pytorch = "pytest --pylint --mypy --black --isort --cache-clear -ra -v --cov geometric_kernels --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml -o junit_family=xunit2 --ignore='tests/integration/gpflow' && task lint_pytorch"

# Numpy
lint_numpy = "pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint geometric_kernels --ignore='tests/integration/gpflow' --ignore='tests/integration/gpytorch'"
quicktest_numpy = "pytest -x --ff -rn -wignore --ignore='tests/integration/gpflow' --ignore='tests/integration/gpytorch'"
check_format_numpy = "pytest -v --cache-clear --black --isort -m 'black or isort' --ignore='tests/integration/gpflow' --ignore='tests/integration/gpytorch'"
test_numpy = "pytest --pylint --mypy --black --isort --cache-clear -ra -v --cov geometric_kernels --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml -o junit_family=xunit2 --ignore='tests/integration/gpflow' --ignore='tests/integration/gpytorch' && task lint_pytorch"

black = "black ."
isort = "isort --atomic -y"
format = "task isort && task black"

[tool.black]
line-length = 95
target-version = ['py37']
# Remaining settings for compatibility with black
# See https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 95