[tool.poetry]
name = "GeometricKernels"
version = "0.1.0"
description = "A Python Package for Geometric Kernels"
authors = ["Geometric Kernel Devs"]
packages = [{include = "geometric_kernels", from = "."}]

[tool.poetry.dependencies]
python = "^3.7"
jupyterlab = "^3.1.1"
seaborn = "^0.11.1"
gpflow = "^2.2.1"
potpourri3d = "^0.0.4"
robust_laplacian = "^0.2.2"
meshzoo = "^0.7.5"
polyscope = "^1.2.0"
tensorflow = "^2.6.0"
tensorflow-probability = "^0.13.0"
eagerpy = "^0.30.0"

[tool.poetry.dev-dependencies]
mypy = "0.711"
pylint = "2.3.1"
pytest = "^5.3.5"
black = { version = "*", allow-prereleases = true }
pytest-cov = "^2.8.1"
pytest-mypy = "^0.6.1"
pytest-pylint = "^0.17.0"
taskipy = "^1.2.0"
pytest-black = "^0.3.8,!=0.3.10"
pytest-isort = "^1.0.0"
gpytorch = "^1.5.0"

[tool.taskipy.tasks]
lint = "pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint geometric_kernels"
mypy = "pytest --mypy --cache-clear -m mypy -v --implicit-reexport"
quicktest = "pytest -x --ff -rN -Wignore"
test = "pytest --pylint --mypy --black --isort --cache-clear -ra -v --cov geometric_kernels --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml -o junit_family=xunit2 && pytest --pylint --cache-clear -m pylint --pylint-rcfile=extrapylint geometric_kernels"
black = "black ."
isort = "isort --atomic -y"
format = "task isort && task black"
check_format = "pytest -v --cache-clear --black --isort -m 'black or isort'"

[tool.black]
line-length = 95
target-version = ['py37']
# Remaining settings for compatibility with black
# See https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 95